### ISSUE TITLE
Publish RenderTest as reusable component in @deck.gl-test-utils

### ISSUE THREAD

**Issue by jianhuang01** [uber/deck.gl#1423]
- [x] Create new sub-module `deck.gl-test-utils`
- [x] Expose render test as reusable utility in `deck.gl-test-utils`
- [x] Move deck.gl independent test classes to `probe.gl/test`
- [x] Make the `testLayer` function independent of `tape` 
- [x] Update all tests to use `testLayer` and remove deprecated life cycle test methods. #1500
- [x] finalize docs and whats-new update. #1499
- [x] Fix new style render tests #1501
- [x] Catch exception in RenderTest.run()
- [x] Api & Doc audit
