### ISSUE TITLE
Website Examples Issue Tracker

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#1873]
#### Background
- tracker for any issues resulting from #1835. Please add any additional issues here.

General Issues
  - [x] Transitions between examples are lost. This can either be restored by reverting the DeckGL/Map nesting, or maybe through initializing the new map with the old state before setting the new state.
  - [x] White flash when switching between examples in  website. Since Map is mounted/unmounted. 
  - [x] React throws propType warning when using `controller: true`

Example-Specific 
  - [x] home renders too big
  - [x] arc-layer renders but can't click on arcs
  - [x] tagmap-layer renders but does not update when zoom in/out (fixed by #1994)
  - [x] brushing-layer renders only dots
  - [x] plot, point cloud - OrbitController is not working
  - [x] trips - trip lines not rendered
  - [x] point-cloud example, zoom & projection are changed.

Fixed
  - [x] Website no longer builds from source. Finds submodules in `../node_modules`.
  - [x] icon does not render
  - [x] home does not render

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding

**Comment by Pessimistress** [comment]
`npm run start-local` in website examples are broken on master.
