### ISSUE TITLE
ScreenGridLayer issue tracker

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#1987]
- [x] QuantizeScale output doesn't match between CPU and GPU (Set gpuAggregation to true in render test)
- [x] Vertex shader using UBO makes it fail under WebGL1, need WebGL1 version of the shader where uniforms are provided directly.
#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [x] Test
