### ISSUE TITLE
Mapbox Custom Layer Integration

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2132]
#### Background 
Mapbox Custom Layer API is available on branch, time do an initial integration.

See also 
- https://github.com/mapbox/mapbox-gl-js/pull/7039
- #92 

#### Breakdown
- [x] Prepare `Deck` for use with external WebGL context and rendering control #2133 
- [x] Initial API integration example #2134 
- [x] 2D deck/mapbox interleaving example #2264 
- [x] Define API for deck.gl and mapbox layers (Flesh out `DeckLayer`)
- [x] Solve matrix and depth buffer integrations
- [x] Picking?

#### To Do List 
  - [x] Add label and assign to milestone 
  - [x] Coding
  - [x] Doc update
  - [x] Whats new update 
  - [x] Test
