### ISSUE TITLE
deck.gl v6.1 release checklist

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2235]
Also see [luma.gl release checklist](https://github.com/uber/luma.gl/issues/688)

## Code

- [ ] Check all issues in [milestone](https://github.com/uber/deck.gl/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A6.1.0)

## Website

- [ ] Add messages for Transform Feedback examples when running under WebGL1 #2252 (Ravi)
- [ ] Check links (Ravi)
- [ ] Update LNGLAT mode doc on `6.1-release` branch (@georgios-uber)
- [x] Update What's New (@ibgreen)
- [x] Update website links to 6.1-release (@jianhuang01 )
- [x] Convert internal publishing guidelines to markdown deck.gl/dev-docs (@ibgreen) #2236 
- [x] Integrate JSON browser publishing into website publishing (@ibgreen ) #2238 

## Testing (see #2070)

- [x] Test that production bundling works with "sideEffects" (@ibgreen) 
- [ ] Test examples on Chrome (initial round done) (Xiao Kai)
- [ ] Test examples on Safari (Xiao Kai)
- [ ] Test examples on Edge (Ravi)
- [ ] Test examples on Linux (@jianhuang01 )
- [ ] Test examples on IE11 (Xiao Kai) - P2

### Testing on Edge version 42.17134.1.0

     - [ ] GeoJsonLayer (polygons) not rendering error : "deck: error while initializing SolidPolygonLayer TypeError: Function expected"

<img width="1241" alt="geojsonlayer_" src="https://user-images.githubusercontent.com/9502731/44691044-e2245d00-aa11-11e8-9f99-d77c372fa425.png">

     - [ ] Trip Routes: Buildings not rendered (don't see any errors in console)

![trip-layer-no-buildings](https://user-images.githubusercontent.com/9502731/44755041-52e27c80-aad9-11e8-8420-3b1637cd38f3.png)

     - [ ] PolygonLayer in LayerBrowser example (no filled polygons, when extruded just renders a thin outline)

![polygonlayer-2](https://user-images.githubusercontent.com/9502731/44755157-d13f1e80-aad9-11e8-8245-be2086bb3dd4.png)
![polygon-layer](https://user-images.githubusercontent.com/9502731/44755161-d43a0f00-aad9-11e8-860c-89d15e8be4bc.png)

     - [ ] ScreenGridLayer in LayerBrowser , no re-aggregation when viewport is changed
![sg-no-re-aggregationwhenviewportchanges](https://user-images.githubusercontent.com/9502731/44755201-09def800-aada-11e8-95b9-a612855a663a.png)

    - [ ] ContourLayer in LayerBrowser, no rendering (#2242)
![conturlayer](https://user-images.githubusercontent.com/9502731/44755217-16635080-aada-11e8-851c-646cc7558a65.png)
