### ISSUE TITLE
6.2 CHECKLIST

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2323]
Also see [luma.gl release checklist](https://github.com/uber/luma.gl/issues/710)

## Code

- [x] Check all issues in [milestone](https://github.com/uber/deck.gl/issues?q=is%3Aopen+is%3Aissue+milestone%3A6.2.0)

- [x] Publish Alpha versions
- [x] Host website
- [x] Cut release branches (after initial testing on Chrome and Safari)
- [x] Publish Beta versions
- [x] Publish Production version.

## Website

- [x] Verify whats-new and upgrade guide
- [x] Check links
- [x] Run all examples
- [ ] Update LNGLAT mode doc on branch (@georgios-uber) (from 6.1, is this done? )

## Testing (see #2070)

- [x] Test examples on Chrome (Xiaoji)
- [x] Test examples on Safari (Xiaokai)
- [x] Test examples on Edge (Ravi)
- [x] Test examples on Linux (Xiaoji)
- [x] Test examples on IE11 (P2)

- [ ] Test with any external apps.
