### ISSUE TITLE
6.3 CHECKLIST

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#2441]
- [x] Verify whats-new
- [x] Verify upgrade-guide
- [ ] Verify all 6.3 issues are closed or move out.

- [ ] Website (docs and example) testing :
    - [x] Testing on Chrome
    - [ ] Testing on Safari 
    - [x] Testing on Firefox 
    - [x] Testing on Edge

**Comment by 1chandu** [comment]
6.3 is published, closing.
