### ISSUE TITLE
Effects (Experimental) Tracking Task

### ISSUE THREAD

**Issue by person594** [uber/deck.gl#253]
**Effect Manager**
- [x] Initial EffectManager and Effect base class
- [x] Integration with DeckGL react component
- [ ] Make effects work with new modelMatrix support on dev (see meter offset scatterplot in example, especially when rotated out of the plane).

**Reflection Effect**
- [x] Create initial ReflectionEffect class
- [x] Add to npm start example
- [x] Fix washed out graphics

**Shadowmap Effect**
- [ ] review shadowmap example in luma.gl
- [ ] Create initial effect layer
- [ ] Example (perhaps with moving sun?)

**Distance Blur Effect**
- [ ] distance blur

**Additional Effects**
- [ ] fog
- [ ] SSAO
- [ ] AA

**Comment by person594** [comment]
https://cloud.githubusercontent.com/assets/6497889/20718250/5820043c-b658-11e6-8513-196fb4a420b5.png

Current reflection effect on arcs -- I am looking into addressing the "washed-out" effect now.

**Comment by shaojingli** [comment]
No longer valid.
