### ISSUE TITLE
OrthographicView issue tracker

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2622]
- [x] [zoom is reversed](https://github.com/uber/deck.gl/issues/2447)
- [x] default zoom/minZoom/maxZoom values should be updated after switching to logarithmic scale
- [x] [default state is not populated](https://github.com/uber/deck.gl/issues/2580)
- [x] improve documentation
- [x] project module throws error if `zoom < 0`
- [x] zoom center does not stay under pointer
