### ISSUE TITLE
v6.4 release tracker

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2623]
- [x] Cut release branch
- [x] Update documentation links
- [x] What's New / Upgrade Guide
- Website testing:

  - [ ] Windows/IE11
         - No website or documentation pages load in IE11.  Same issue occurs on currently live version of website.  Console errors: `SCRIPT438: Object doesn't support property or method 'assign'`
  - [x] Windows/Edge
        - http://pessimistress.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/geojson-layer
`Cannot find linked doc:  docs/layers/solid-polygon-layer.md`
        - Occasional spam of WebGL errors when clicking around between examples.  Occurs on prod website as well. 
`100 WEBGL11163: drawArrays: An enabled vertex array has no buffer.  bundle.js (35,649859)`
        - New deprecation warnings in Arc and Arc Brushing examples:
```
  deck: `ScatterplotBrushingLayer: getColor` is deprecated and will be removed in a later version. Use `getFillColor/getLineColor` instead
bundle.js (46,91854)
 deck: `ScatterplotBrushingLayer: strokeWidth` is deprecated and will be removed in a later version. Use `getLineWidth` instead
bundle.js (46,91854)
 deck: `ScatterplotBrushingLayer: outline` is deprecated and will be removed in a later version. Use `stroked` instead
bundle.js (46,91854)
 deck: `ArcBrushingLayer: strokeWidth` is deprecated and will be removed in a later version. Use `getStrokeWidth` instead
 deck: `ArcLayer: `strokeWidth`` is deprecated and will be removed in a later version. Use ``getStrokeWidth`` instead
```
  - [x] Chrome
        - Documentation/"JSON API reference"/JSONDeck page is not found
        - Lots of deprecated API warnings
        - Lots of "Too many active WebGL contexts" and "Invalid operation" warnings while visiting core layer examples, and occasionally the base map can't show up
        - "Cannot find linked doc:  docs/layers/solid-polygon-layer.md" while visiting Documentation/"Deck.gl API reference"/layers/ PolygonLayer
  - [x] Firefox
		- http://pessimistress.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer: the outline is messed up when zoom in/out 
		- http://pessimistress.github.io/deck.gl/#/documentation/json-api-reference-experimental/json-deck-experimental: link not found
  - [x] Safari
        - Documentation/"JSON API reference"/JSONDeck page is not found
        - Lots of deprecated API warnings
        - Easier to reproduce the issue that the base map can't show up when "There are too many active WebGL contexts on this page, the oldest context will be lost" message shows up
        - "Cannot find linked doc:  docs/layers/solid-polygon-layer.md" while visiting Documentation/"Deck.gl API reference"/layers/ PolygonLayer
  - [x] Mobile/iOS
  - [x] Mobile/Android

**Comment by Pessimistress** [comment]
- [ ] ScatterplotLayer deprecation warning for `getColor`

Need to update all examples that use `ScatterplotLayer`. @XiaokaiUber
