### ISSUE TITLE
Tracker: Project Module Refactor

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2828]
#### Target Use case
- `project` module is the heart of deck.gl
- currently quite complicated
- internal assumptions not clearly documented
- very hard to change

#### Proposed Feature
- [ ] Collect current known limitations and issues with project module
- [ ] Define how a `projectV2` module should work, including changes to interpretation of various coordinate system modes if needed.

Limitations
- [ ] World pixel scale in shaders variable
- [ ] Hard to match external sources (e.g. lights) to internal shader coords.
- [ ] Pixels in `COORDINATE_SYSTEM.IDENTITY`: #2824 
- [ ] Fix application of model matrices to vertices in e.g. hexagon layer in lnglat mode.
- [ ] Support rotation model matrices in LNGLAT Mode, based on coordinate origin?
...

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by tgorkin** [comment]
Related enough to #2151 to consolidate?

**Comment by tgorkin** [comment]
Closing this as work in favor of project system refactor work done in 8.0 milestone covered by #3831
