### ISSUE TITLE
deck.gl v4.0 Release Work Tracking Task

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#284]
### Hygiene Features
- [x] Use `react-map-gl` 2.0.0 official release  (or "final beta")
- [x] Use `viewport-mercator-project` 3.0.0 official release  (or "final beta")
- [x] Split out Mercator related calculations from MercatorViewport, leave in `viewport mercator project`
- [x] Use `luma.gl` 3.0.0 official release (or "final beta")
- [x] Reduce npm dependencies, move example dependencies out of main
- [x] Move to webpack 2 / buble
- [x] yarn support

### Demo/Documentation Site
- [x] Review documentation for model matrix
- [x] Add deprecation warnings and deprecation docs
- [ ] Make gallery examples stand-alone (if possible)
- [x] Make demo stand-alone (separate package.json)
- [x] New showcases for `PointCloudLayer` etc
- [x] Link to v3 documentation

### Non-Mercator Viewport Support
- [x] Move `Viewport`s from `viewport-mercator-project` beta into deck.gl
- [x] Move Viewport docs into deck.gl
- [x] Create an example using non-mercator viewports

### Event Handling (react-map-gl independent)
- [ ] Add example with scrolling map and fix coordinate translation bug.
- [x] Implement an event handling system that works naturally with non-mercator viewport
- [x] Target rotate camera

## Existing Layers
- [x] Correct lighting system for all extruded layers

### API Audit
- [x] GeoJsonLayer
- [x] GridLayer
- [x] HexagonLayer
- [x] PointCloudLayer

### 64 bit layers
- [x] PolygonLayer64
- [x] PathLayer64
- [x] IconLayer64
- [x] PointCloudLayer64
- [x] ScatterplotLayer64 - convert to subclass
- [x] ArcLayer64 - convert to subclass
- [x] LineLayer64 - convert to subclass
- [x] ChoroplethLayer64 - convert to subclass
- [x] ArcLayer64 - convert to subclass
- [x] GridLayer64
- [x] HexagonLayer64

### IconLayer
- [ ] Correctly handling async load of icon resources

### Layer updates
- [x] `Layer.defaultProps` - support in lib and update layers
- [x] `Layer.getShaders` - update layers
- [x] Support for Model Matrix for METER_OFFSETS mode
- [x] Add controls to main demo for model matrix
- [x] Single framebuffer readback for picking

### Stability
- [x] Add JavaScript benchmarking support
- [x] Add rendering tests to catch rendering regressions
- [x] Add GLSL benchmarking support (initial perf query has been in luma.gl)
- [x] Unit Test driver for layers (i.e. initialize and instantiate all attributes)
- [x] Add layer prop controls to main example so that we can manually test changing props.
- [x] >200 unit tests
- [ ]  unit tests for each layer

### Examples
- [x] Hello world example (minimal code and dependencies)
- [x] Main example (layer browser) - convert to stand-alone
- [x] Main example UI refresh / simplification
- [x] Main example (add model matrix controls)
- [x] Move exhibits to react-map-gl (they deal with mapbox-gl-js/webpack issues)
- [x] Remove exhibits from deck.gl and reference react-map-gl exhibits from deck.gl docs.
- [x] 3D surface example
- [ ] Tree shaking example (P2)

### ChoroplethLayers
- [x] Add `log.once` warnings to the ChoroplethLayer constructors indicating that they are deprecated.
- [x] Move ChoroplethLayer, ChoroplethLayer64 and ExtrudedChoroplethLayer64 to deprecated folder
- [x] Move the sample EnhancedChoroplethLayer to example folder
- [x] Document as deprecated or removed in "breaking changes", "what's new" and individual layer docs

**Comment by Pessimistress** [comment]
Shall we add a 64-bit version of the PathLayer? @gnavvy @shaojingli

**Comment by ibgreen** [comment]
Closing as there are bugs for the remaining open tasks.
