### ISSUE TITLE
Tracker: ScenegraphLayer

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2871]
#### Description

- [x] Finish integration with loaders.gl (data async prop)
- [x] Avoid recreating scenegraph everytime props change https://github.com/uber/deck.gl/blob/master/modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js#L141
- [x] Move the vertex and fragment shaders out of the JS file to align with other layers.
- [x] Delete old scenegraph when new one needs to be created
- [x] Finish docs

**Comment by georgios-uber** [comment]
Done
