### ISSUE TITLE
[7.0] SimpleMeshLayer issue tracker

### ISSUE THREAD

**Issue by Pessimistress** [uber/deck.gl#2890]
- [x] Bug: transform attributes never update. This is due to https://github.com/uber/deck.gl/blob/master/modules/mesh-layers/src/utils/matrix.js#L167 using a stale version of a layer - it always retrieves the props from the layer instance at initialization.
- [x] Feature request: add `wireframe` mode to draw meshes using `GL.LINE` (see avs.auto demo)
- [x] Support using loaders.gl to fetch mesh, similar to https://github.com/uber/deck.gl/blob/master/modules/mesh-layers/src/scenegraph-layer/scenegraph-layer.js#L40
- [x] Attribute validation is overly strict: missing texCoords should be allowed

**Comment by tsherif** [comment]
@Pessimistress for wireframe, just draw the same thing with gl.LINE_STRIP? Or do we we want to re-organize the mesh so the wireframe shows the actual mesh?

**Comment by Pessimistress** [comment]
The streetscape.gl version just used `gl.LINE_STRIP`.

**Comment by Pessimistress** [comment]
When the mesh attributes are invalid, the layer emits an error `deck.gl: undefined`. Can we add a readable message to this, considering this is going to be user-facing?
