### ISSUE TITLE
7.0 Release Checklist

### ISSUE THREAD

**Issue by tgorkin** [uber/deck.gl#2892]
- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@tgorkin )
- [x] Verify all 7.0 issues are closed or move out (@tgorkin )
- [ ] Verify all API changes are documented (@Pessimistress )
- [ ] Website (docs and example) testing: [staging](https://jianhuang01.github.io/deck.gl/)
    - [ ] Testing on Chrome (@1chandu )
    - [x] Testing on Safari (@jianhuang01 )
    - [x] Testing on Firefox (@tgorkin )
    - [ ] Testing on Edge + IE11 (@tsherif)
    - [ ] Testing on iOS (@Pessimistress )
    - [ ] Testing on Android (@Pessimistress)

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by Pessimistress** [comment]
- [ ] `isWebGL2` is returning true in Safari. Broken example: http://pessimistress.github.io/deck.gl/#/examples/core-layers/screen-grid-layer

@tsherif

**Comment by tsherif** [comment]
The problem is that we have several versions of `isWebGL2`. The broken one is https://github.com/uber/luma.gl/blob/master/modules/webgl-state-tracker/src/utils/utils.js#L10-L13

It breaks after the gl constant replacement. I'll remove that function use the one in webgl/webgl-utils everywhere: https://github.com/uber/luma.gl/blob/master/modules/webgl/src/webgl-utils/webgl-checks.js#L12-L19

**Comment by tgorkin** [comment]
Testing results with Firefox 66.0.2 (64-bit) on MacOSX:

**General warnings on most pages:**
Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting.
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
luma: `Attribute.instanced` is deprecated and will be removed in a later version. Use `undefined` instead
luma: accessor size mismatch
luma: `Buffer.type` is deprecated and will be removed in a later version. Use `Buffer.accessor.type` instead
luma: Model.render() is deprecated. Use Model.setUniforms() and Model.draw()

**Line Layer Example**
deck: `LineLayer: getStrokeWidth` is deprecated and will be removed in a later version. Use `getWidth` instead

**Hexagon Layer Example**
TypeError: "n.centroid is undefined"
    _renderTooltip http://pessimistress.github.io/deck.gl/bundle.js:61
    render http://pessimistress.github.io/deck.gl/bundle.js:61
    Oo http://pessimistress.github.io/deck.gl/bundle.js:40
    Do http://pessimistress.github.io/deck.gl/bundle.js:40
    pa http://pessimistress.github.io/deck.gl/bundle.js:40
    ha http://pessimistress.github.io/deck.gl/bundle.js:40
    Za http://pessimistress.github.io/deck.gl/bundle.js:40
    Wa http://pessimistress.github.io/deck.gl/bundle.js:40
    Ga http://pessimistress.github.io/deck.gl/bundle.js:40
    Ua http://pessimistress.github.io/deck.gl/bundle.js:40
    ba http://pessimistress.github.io/deck.gl/bundle.js:40
    enqueueSetState http://pessimistress.github.io/deck.gl/bundle.js:40
    setState http://pessimistress.github.io/deck.gl/bundle.js:32
    _onHover http://pessimistress.github.io/deck.gl/bundle.js:61
    onHover http://pessimistress.github.io/deck.gl/bundle.js:1
    callLayerPickingCallbacks http://pessimistress.github.io/deck.gl/bundle.js:1
    callLayerPickingCallbacks http://pessimistress.github.io/deck.gl/bundle.js:1
    pickClosestObject http://pessimistress.github.io/deck.gl/bundle.js:1
    pickObject http://pessimistress.github.io/deck.gl/bundle.js:1
    _pickAndCallback http://pessimistress.github.io/deck.gl/bundle.js:1
    _onRenderFrame http://pessimistress.github.io/deck.gl/bundle.js:1
    value http://pessimistress.github.io/deck.gl/bundle.js:1
    value http://pessimistress.github.io/deck.gl/bundle.js:1
    t http://pessimistress.github.io/deck.gl/bundle.js:1
bundle.js:40:71999

**Icon Layer Example**
Meteorites example not rendering

**GeoJsonLayer (Paths) Example**
Not rendering
luma: Found instanced attributes on non-instanced model transform-model
Error: WebGL warning: drawArrays: One active vertex attrib (if any are active) must have a divisor of 0.

**ScreenGridLayer Example**
Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
Error: WebGL warning: drawArraysInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)
luma: `Buffer.size` is deprecated and will be removed in a later version. Use `Buffer.accessor.size` instead
luma: `Buffer.bytes` is deprecated and will be removed in a later version. Use `Buffer.byteLength` instead
luma: `Buffer.instanced` is deprecated and will be removed in a later version. Use `Buffer.accessor.divisor` instead

**ArcLayer Example**
deck: `ArcLayer: getStrokeWidth` is deprecated and will be removed in a later version. Use `getWidth` instead

**TileLayer Example**
tile loading takes 1-5 seconds in my testing

**Brushing Layer Example**
luma: `project_scale` has been removed. Use `project_size` instead
luma: `project_to_clipspace` has been removed. Use `project_common_position_to_clipspace` instead

**BitmapLayer docs page**
Missing example 
H3HexagonLayer and H3ClusterLayer docs - shows PolygonLayer example in docs page 

**TileLayer docs page**
Unhandled promise rejection Error: "deck.gl: GeoJSON does not have type"

**Comment by 1chandu** [comment]
> The problem is that we have several versions of `isWebGL2`. The broken one is https://github.com/uber/luma.gl/blob/master/modules/webgl-state-tracker/src/utils/utils.js#L10-L13
> 
> It breaks after the gl constant replacement. I'll remove that function use the one in webgl/webgl-utils everywhere: https://github.com/uber/luma.gl/blob/master/modules/webgl/src/webgl-utils/webgl-checks.js#L12-L19

@tarek related issue: https://github.com/uber/luma.gl/issues/797

**Comment by 1chandu** [comment]
Testing on Chrome:

- Examples:

 - [ ] Hexagon layer : crashes while picking
```
    bundle.js:40 TypeError: Cannot read property '1' of undefined
    at An._renderTooltip (bundle.js:61)
    at An.render (bundle.js:61)
```

- [ ] Tile layer  : white screen while zooming in for more than 2/3 seconds
   could be related to tile loading, should we just display old tiles while new ones being loaded?

- [ ] Brushing layer : errors
```
`project_scale` has been removed. Use `project_size` instead
`project_to_clipspace` has been removed. Use `project_common_position_to_clipspace` instead
```

- Documentation

- [ ] Too many links for older docs, should we include just include only link to major version for older revision, i.e. remove 15.2, `5.2, `5.1` but just keep `5.0`

- [ ] Upgrade Guide:   Confusing heading/subheadings.   (Module : Breaking Changes Deprecations), match the formatting of 6.4 to 7.0 section to 6.3 to 6.4 section.

**Comment by jianhuang01** [comment]
Icon Layer example not working (Firefox only) and TileLayer docs page example crashes (Firefox only) are caused by @babel/polyfill, once remove it the two examples work well, but without the  @babel/polyfill, IE won't work.

**Comment by jianhuang01** [comment]
Test on Safari
- [ ] screen grid layer example crashes
- [ ] deckgl-api-reference/layers/grid-layer link is wrong

**Comment by tsherif** [comment]
Deck.gl site doesn't work at all in Edge or IE. Just a blank white page.
In Edge: "Expected identifier, string or number"
In IE: "Invalid character"
