### ISSUE TITLE
Tracker: JSON/Python API enhancements

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#3079]
#### Target Use case

Additional flexibility in the JSON API, in particular for the python bindings.

#### 7.3
- [x] Better expression parser for accessors, at minimum support CSV
![Image Pasted at 2019-5-7 16-31](https://user-images.githubusercontent.com/7025232/57395262-7daec580-717c-11e9-98e0-c375c16a0a01.png)
- [x] Integrate expression evaluator for accessors
- [x] Built in tooltips

#### 7.4
- [ ] Built in time slider

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by ibgreen** [comment]
@ajduberstein

**Comment by tgorkin** [comment]
Closing this out in favor of #3640
