### ISSUE TITLE
7.1 Release Checklist

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#3173]
- [x] Verify whats-new (@Pessimistress)
- [x] Verify upgrade-guide (@Pessimistress)
- [x] Verify all 7.1 issues are closed or move out (@tgorkin)
- [x] Verify all API changes are documented
- [x] Documentation: Update source file urls to point to 7.1-release branch
- [x] Website (docs and example) testing: [staging](http://pessimistress.github.io/deck.gl/#/documentation/overview/whats-new)
    - [x] Testing on Chrome (@jianhuang01)
    - [x] Testing on Safari (@xintongxia)
    - [x] Testing on Firefox (@1chandu) 
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress)
    - [x] Testing on Android (@Pessimistress)

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by Pessimistress** [comment]
Mobile:
- [ ] What's new images are squashed
- [ ] IconLayer example: picking does not work in iOS Safari
- [ ] TripsLayer thumbnail on the "examples" page goes to the brushing example

**Comment by 1chandu** [comment]
Firefox :


 - [ ] Postprocessing doc page (Console Errors/Warnings)
  Error: WebGL warning: getContext: Disallowing antialiased backbuffers due to blacklisting. dist.min.js:1:76341
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

 - [ ] Bitmap layer doesn't render anything.

 - [ ] ColumnLayer (doc page):  `stroked` doesn't render the stroke line (with extuded off)

 - [ ] ColumnLayer (doc page) : crash while changing `diskResolution` and `radius`
Error: ColumnLayer-program  Bad uniform edgeDistance bundle.js:1:76706
ColumnLayer-program  Bad uniform edgeDistance NaN

 - [ ] ColumnLayer (doc page) : `discResolution` controller changes between 0 and 1 instead of actual prop limits.

**Comment by Pessimistress** [comment]
The PathLayer issue is just z-fighting. We can disable depth test for this demo.

**Comment by tsherif** [comment]
Edge:
- [ ] Icon layer example not working. Only console error is about NPOT texture

IE:
- [ ] All examples broken except screengridlayer, hexagon layer, tile layer, 3D surface
- [ ] Icon layer crashes the page
- [ ] Trips-data-decoder.js, highway-accidents-decoder.js,  highway-roads-decoder.js, arc-data-decoder.js, hash-tags-decoder using include ES6 code which breaks
- [ ] “fetch” undefined in point cloud layer example
- [ ] None of the showcase links work

**Comment by jianhuang01** [comment]
Chrome:
- [ ] Random warning "Unable to perform style diff: Unimplemented: setLayerProperty"

**Comment by xintongxia** [comment]
Safari:
- [ ] Kepler.gl link is broken (not restricted to safari)

**Comment by 1chandu** [comment]
>  ScreenGridLayer warning:
[Warning] deck: ScreenGridAggregator: GPU Aggregation not supported, falling back to CPU (bundle.js, line 64)

This is expected and fine, should go away, if you set `gpuAggregation` prop to false. We can change this to `info` from `warning` too.
