### ISSUE TITLE
7.2 Release Checklist

### ISSUE THREAD

**Issue by tgorkin** [uber/deck.gl#3396]
- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@Pessimistress  )
- [x] Verify all issues in milestone are closed or move out (@tgorkin )
- [x] Verify all API changes are documented (@Pessimistress )
- [x] Website (docs and example) testing: [staging](https://1chandu.github.io/deck.gl/#/)
    - [x] Testing on Chrome (@ajduberstein)
    - [x] Testing on Safari (@jianhuang01)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress )
    - [x] Testing on Android (@Pessimistress)
- [x] Cut 7.2-release branch after all fixes
- [x] Update website doc urls to point to `7-2-release` branch  (@1chandu )
- [x] Update 7.2 badge to point to 7.2 branch on Overview page. (@1chandu)
- [x] Update luma.gl dependency to 7.2 prod (@1chandu )
- [x] Publish 7.2 prod version.  (@1chandu )

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue

**Comment by jianhuang01** [comment]
Safari Testing
1. TripsLayer example is extremely slow
2. Geojson (paths) example is down 
3. Heatmap layer document page is down
5. Data Filter example doesn't show data.

**Comment by tsherif** [comment]
Edge: 👍 
IE: Site does not load at all. There's untranspiled ES6 in the site bundle.js.

**Comment by tsherif** [comment]
IE: Offending dependency (or at least one of them) is [kdbush](https://www.npmjs.com/package/kdbush). Not sure what it's used for, but finding e.g. this line untranspiled in the bundle: https://github.com/mourner/kdbush/blob/master/src/index.js#L14

**Comment by ajduberstein** [comment]
Chrome testing: 💯

A few warnings but all the examples are functional.

`deck: e.componentName not specified` on main page
Screen grid layer produces a warning 95 times, `[.WebGL-0x7fef75911400]RENDER WARNING: Render count or primcount is 0.`

**Comment by tgorkin** [comment]
Doc version badges on https://1chandu.github.io/deck.gl/#/documentation/overview/introduction need to be updated.  Need to add 7.1 and 7.2.
<img width="787" alt="Screen Shot 2019-08-07 at 4 33 38 PM" src="https://user-images.githubusercontent.com/529280/62664644-35e13b00-b931-11e9-977a-048c2acfac57.png">

**Comment by 1chandu** [comment]
Firefox 👍 

Following issue applicable to all browsers 

- [ ] `Data Filter` demo doesn't render any thing, has following error in console : `earthquakes-decoder.js:3 Uncaught ReferenceError: require is not defined
    at earthquakes-decoder.js:3`

**Comment by 1chandu** [comment]
Kepler integration:

- [ ] We added a new module parameter, `mousePosition`, it is causing a crash if layer happens have a `mousePosition` prop :
`layers-pass.js:159 Uncaught TypeError: Cannot assign to read only property 'mousePosition' of object '[object Object]'`
Even if did use `brushing` extension, should we use a different to avoid overwrite or  overwrite with a warning and avoid crash? 
- [ ] Update upgrade guide to specify removal of `use64bitProjection` and `is64bitEnabled` from Layer class.

**Comment by Pessimistress** [comment]
iOS:

- [ ] Data filter example slider is covered by nav bar

**Comment by tsherif** [comment]
@ibgreen Looks like that kdbush module is pulled in by the Jupyter notebook stuff? Any reason that wouldn't be transpiled properly?

```bash
yarn why v1.13.0
[1/4] 🤔  Why do we have the module "kdbush"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "kdbush@3.0.0"
info Reasons this module exists
   - "_project_#@deck.gl#jupyter-widget#mapbox-gl#supercluster" depends on it
   - Hoisted from "_project_#@deck.gl#jupyter-widget#mapbox-gl#supercluster#kdbush"
```

**Comment by Pessimistress** [comment]
@tsherif the icon layer example uses supercluster.

**Comment by tsherif** [comment]
@Pessimistress Any thoughts on why it isn't getting transpiled to ES5?

**Comment by Pessimistress** [comment]
@tsherif 	you can manually whitelist it in https://github.com/uber/deck.gl/blob/master/website/webpack.config.js#L49

**Comment by tsherif** [comment]
Was able to fix the supercluster issue, but now there's some ES6 getting into the bundle from math.gl. Seeing several calls to `Reflect.construct` in there which crash the site in IE.

**Comment by tsherif** [comment]
`Reflect` references are from `babel-plugin-transform-builtin-extend`: https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend/issues/10

I'm not sure why they're not getting transformed, though.

**Comment by 1chandu** [comment]
- [ ] Crash in loaders.gl while running website locally in 7.2-release branch (same issue in master)

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (bundle.js:99234)
    at Module../node_modules/@loaders.gl/las/dist/esm/laz-perf.transpiled.js (bundle.js:156414)
    at __webpack_require__ (bundle.js:20)
    at Module../node_modules/@loaders.gl/las/dist/esm/laslaz-decoder.js (bundle.js:98853)
    at __webpack_require__ (bundle.js:20)
    at Module../node_modules/@loaders.gl/las/dist/esm/parse-las.js (bundle.js:156430)
    at __webpack_require__ (bundle.js:20)
    at Module../node_modules/@loaders.gl/las/dist/esm/las-loader.js (bundle.js:98804)
    at __webpack_require__ (bundle.js:20)
    at Module../node_modules/@loaders.gl/las/dist/esm/index.js (bundle.js:98783)
```
