### ISSUE TITLE
Tracker: @deck.gl.json as generic component wrapping solution

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#3557]
#### Target Use case
- An increasing number bindings to other languages are being developed on top of deck.gl (pydeck, R, JSON, ...)
- Parallel efforts are creating similar bindings, duplicating effort.
- A shared system could increase productivity and quality.

## Description

Refactor @deck.gl/json into a generic component wrapping system for prop based components, with the JSON representation as a generic cross-language intermediary, per [RFC](https://github.com/uber/deck.gl/blob/master/dev-docs/RFCs/vNext/component-wrapping-rfc.md)

#### @deck.gl/json module
- [x] Add label and assign to milestone
- [x] Remove any deck.gl dependencies, refactoring `configuration`
- [x] API cleanup
- [x] Update tests
- [x] Update docs
- [x] What's New

#### JSON Browser Example
- [x] Move example out of `experimental` folder
- [x] Move deck.gl specific code from @deck.gl/json to json-browser example
- [x] Update JSON sample files

#### website
- [x] Integrate the JSON browser into the web page proper (increase discoverability and ensure it is part of mainstream testing).
- [x] Decide if we keep the 'https://deck.gl/json' link alive.

#### open issues
- [x] Do we keep the `JSONLayer`? It no longer fits in any module. Add as experimental example?
