### ISSUE TITLE
Tracker 3DTiles

### ISSUE THREAD

**Issue by xintongxia** [uber/deck.gl#3559]
Documentation
- [x] Address comments #3508 @xintongxia 
- [x] Add API doc to website  @xintongxia 
 
Layer
- [x] Address comments #3523 @jianhuang01 

Example
- [x] Add 3d tiles layer example @jianhuang01
