### ISSUE TITLE
7.3 Release Tracker

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#3591]
- [x] Bump all dependencies (math.gl, probe.gl, loaders.gl and luma.gl)  latest alpha/beta/ prod versions (@1chandu)
- [x] Publish alpha/beta  (@1chandu)
- [x] Bump all examples to latest alpha/beta (@1chandu)
- [x] Stage the website (@1chandu)
- [x] Verify whats-new (@tgorkin )
- [x] Verify upgrade-guide (@Pessimistress  )
- [x] Verify all issues in milestone are closed or move out (@tgorkin )
- [x] Verify all API changes are documented (@Pessimistress )
- [x] Website (docs and example) testing: [staging](http://pessimistress.github.io/deck.gl/#/)
    - [x] Testing on Chrome (@ajduberstein)
    - [x] Testing on Safari (@xintongxia)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress )
    - [x] Testing on Android (@Pessimistress)
- [x] Cut 7.3-release branch after all fixes
- [x] Update website doc urls to point to `7-3-release` branch  (@1chandu )
- [x] Update 7.3 badge to point to 7.3 branch on Overview page. (@1chandu)
- [x] Update luma.gl dependency to 7.3 prod (@1chandu )
- [x] Publish 7.3 prod version.  (@1chandu )

Testing procedure
- access staged doc website
- go through all examples
- verify functionality in control panels
- look for console errors/warnings
- add results of testing as comments on this issue
- Test Playground (JSON Browser) (Instructions:  ?? TBD)

**Comment by SymbolixAU** [comment]
I've been trying the [`BrushingExtension()`](https://github.com/uber/deck.gl/blob/master/docs/api-reference/extensions/brushing-extension.md) the but keep getting the error 

> deck.BrushingExtension is not a constructor

I'm using `https://unpkg.com/deck.gl@^7.3.0-alpha.7/dist.min.js`. 

The new `LightingEffects` seem to work fine

The snippet of code to generate the error is

```js

  const d = new deck.DirectionalLight({
	  color: [255, 255, 255],
	  intensity: 1.0,
	  direction: [-3, -9, -1]
	});
  console.log( d );
  const b = new deck.BrushingExtension();
  console.log( b );

```
And here's a screenshot

![Screen Shot 2019-09-16 at 8 20 25 am](https://user-images.githubusercontent.com/18344164/64928386-f6c0d680-d85a-11e9-8519-8b403074c533.png)

**Comment by 1chandu** [comment]
deck only re-exports everything from `@deck.g;/core` and `@deck.gl/layers` sub modules, `BrushingExtension` is defined in '@deck.gl/extensions' and not re exported.

**Comment by Pessimistress** [comment]
> deck only re-exports everything from @deck.g;/core and @deck.gl/layers sub modules

The pre-bundled version does re-export everything except react and test-utils. It was a bug not including extensions. This was patched in 7.2.4 but we haven't published a new 7.3 alpha yet.

**Comment by SymbolixAU** [comment]
I just tested `7.3.0-beta.1` and no longer see the error.

**Comment by Pessimistress** [comment]
Website test on iOS:
- [ ] HeatmapLayer example crashes
- [ ] Tile3dLayer example - no data rendered

**Comment by tsherif** [comment]
Edge testing: No issues.

**Comment by tsherif** [comment]
IE: Site doesn't load. It's crashing on a `const` declaration in the bundle.

**Comment by 1chandu** [comment]
Firefox:

- [ ] Line Layer (exists in 7.2 too and also occurs in chrome) : some overlapping lines are in black color 

<img width="1792" alt="Screen Shot 2019-09-23 at 10 30 59 AM" src="https://user-images.githubusercontent.com/9502731/65448401-8a5f4d80-dded-11e9-83f5-70bb57df50b9.png">

**Comment by ajduberstein** [comment]
Chrome:
- [ ] Color pickers work in the layer documentation don't seem to work, e.g., [this example's](https://deck.gl/#/documentation/deckgl-api-reference/layers/bitmap-layer) autoHighlight. Worth noting that the color picker works in this [example](https://1chandu.github.io/deck.gl/#/examples/core-layers/scatterplot-layer).

- [ ] Z-fighting in the scatterplot example, though I'm unsure if this is an error:
![image](https://user-images.githubusercontent.com/2204757/65449871-bd571080-ddf0-11e9-865f-928f8fea1586.png)

- [ ] Text sizing on the [CPUGridLayer](https://1chandu.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/cpugrid-layer):

![image](https://user-images.githubusercontent.com/2204757/65450235-8a614c80-ddf1-11e9-8d48-dc348614d59d.png)

Also affects [GridLayer](https://1chandu.github.io/deck.gl/#/documentation/deckgl-api-reference/layers/grid-layer) documentation

- [ ] Might not be an error but the color palette might need to be changed in LineLayer:

![image](https://user-images.githubusercontent.com/2204757/65450657-808c1900-ddf2-11e9-8425-74c619fbce36.png)

- [ ] Not explicitly an error but rapidly increasing the radius on the [HeatmapLayer](https://1chandu.github.io/deck.gl/#/examples/core-layers/heatmap-layer) locks my browser for about 30 seconds.

- [ ] Tile3DLayer gives 9,479 logged instances of `Tile load cancelled`. The visualization itself seems patchy. Not my browser test but it appears not to render at all on Safari.

![image](https://user-images.githubusercontent.com/2204757/65451443-06f52a80-ddf4-11e9-83bc-04778eb28269.png)

- [ ] Nit: Not a visualization error but `Playground` under `Declarative Layers` links to the full path of https://deck.gl/json instead of the relative path of /json

**Comment by 1chandu** [comment]
Update on iOS crash:
With beta.6, the crash is fixed, but on the iOS device I only see single color instead of full spectrum, also blending seems wrong :
![IMG_A8A64ABE7AFD-1](https://user-images.githubusercontent.com/9502731/65638835-d223d780-df9b-11e9-9954-018bd67049cf.jpeg)

From #3554 , @tsherif mentioned there could be a bug in ANGLE implementaiton that is affecting windows machine similarly (i.e only showing one color).

I debugged this more, and see the max weight calculation is always 0, could be an issue specific to KDE implementation / additive blending that is only affecting iOS device and windows.

**Comment by 1chandu** [comment]
HeatmapLayer rendering issues are root caused to ANGLE , when using 1X1 Texture as render target, until this issue is fixed by ANGLE, adding `weightsDomain` so custom domain can be specified as a workaround.
