### ISSUE TITLE
8.0 Release Tracker

### ISSUE THREAD

**Issue by tgorkin** [uber/deck.gl#3983]
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release (@Pessimistress)
- [x] Publish alpha/beta  (@Pessimistress)
- [x] Bump all examples to latest alpha/beta (@Pessimistress)
- [x] Stage the website (@Pessimistress)
- [x] Verify whats-new (@Pessimistress)
- [x] Verify upgrade-guide (@Pessimistress)
- [x] Verify all issues in milestone are closed or move out (@tgorkin)
- [x] Verify all API changes are documented (@Pessimistress)
- [x] Website (docs and example) testing: [staging]()
    - [x] Testing on Chrome (@tsherif)
    - [x] Testing on Safari (@xintongxia)
    - [x] Testing on Firefox (@1chandu)
    - [x] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress)
    - [x] Testing on Android (@Pessimistress)
- [x] Cut 8.0-release branch after all fixes (@Pessimistress)
- [x] Update website doc urls to point to `8.0-release` branch (@Pessimistress)
- [x] Publish 8.0 prod version.

Testing procedure
- access [staged doc website](http://pessimistress.github.io/deck.gl/)
- go through all examples and verify functionality in control panels
- go through all layers in [JSON playground](http://pessimistress.github.io/deck.gl/playground/)
- check visible results for regressions and console for errors/warnings
- add results of testing as comments on this issue

**Comment by Pessimistress** [comment]
iOS:

- [ ] 3D surface example: text labels are up side down
- [ ] ScreenGridLayer example: aggregation result is not aligned with the base map

![E775E69D-F924-4B1D-A485-AAE380A2D601](https://user-images.githubusercontent.com/2059298/70772018-0cde1600-1d28-11ea-85c5-82ab466f2d44.jpeg)

**Comment by 1chandu** [comment]
- [ ] TripsLayer Example: when rotating only base map is rotated, also seeing these WebGL errors in console
```
Error: WebGL warning: <SetDimensions>: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one. dist.min.js:1:3763
Error: WebGL warning: generateMipmap: Tex image TEXTURE_2D level 0 is incurring lazy initialization. dist.min.js:1:98609
SecurityError: The operation is insecure. 3d885e11-bb59-6441-8248-c3e996217f58:1:4645
SecurityError: The operation is insecure. 3d885e11-bb59-6441-8248-c3e996217f58:1:4645
SecurityError: The operation is insecure. 3d885e11-bb59-6441-8248-c3e996217f58:1:4645```

**Comment by Pessimistress** [comment]
- [ ] tooltips are behind the canvas when running example apps standalone

**Comment by tsherif** [comment]
Chrome:
- Screen grid layer example not working: `dist.min.js:1 WebGL: INVALID_ENUM: blendEquationSeparate: invalid mode`
- A lot of `Unable to perform style diff: Unimplemented: setLayerProperty, setLayerProperty...`

**Comment by tsherif** [comment]
Edge:
- [ ] Website does not load `SCRIPT1028: SCRIPT1028: Expected identifier, string or number` Looks like it's an object spread operation (not supported in Edge). This is the minified code that produces it:
```
,{map:s=window.mapboxgl}=e;super({canvas:n,...e}),s&&s.Map?this._map=o&&new r.a(Object.assign({},e,{viewState:i,container:t,mapboxgl:s}
```

**Comment by tsherif** [comment]
IE:
- [ ] Website does not load `SCRIPT1004: Expected ';'` Looks like it's async/await calls. Here's the minified code that's producing it: 
```
turn e.map((function(e){return l(e,t)}))}async function s(e,t){return await Promise.all(e.map(e=>h(e,t)))}function u(e,t){const n=l(e.object,t);return e.computed?[n,n[l(e.property,t)]]:[n,n[e.property.name]]}async function c(e,t){const n=aw
```

**Comment by xintongxia** [comment]
Safari

- [ ] Tile3DLayer

```
[Error] WebGL: drawArraysInstanced: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete', or it is a float/half-float type with linear filtering and without the relevant float/half-float linear extension enabled.
	drawArraysInstancedANGLE
	(anonymous function) (dist.min.js:11:346509)
	(anonymous function) (dist.min.js:11:346312)
	(anonymous function) (dist.min.js:6:113997)
	value (dist.min.js:1:79526)
	value (dist.min.js:6:113898)
	value (dist.min.js:11:346176)
	value (dist.min.js:6:125937)
	value (dist.min.js:6:262990)
	(anonymous function) (dist.min.js:1:279026)
	value (dist.min.js:1:278989)
	(anonymous function) (dist.min.js:1:224295)
	forEach
	value (dist.min.js:1:224018)
	(anonymous function) (dist.min.js:1:223360)
	forEach
	value (dist.min.js:1:223255)
	value (dist.min.js:6:92788)
	value (dist.min.js:6:184810)
	value (bundle.js:92:182350)
	value (bundle.js:92:181973)
	za (bundle.js:22:82947)
	Ha (bundle.js:22:85507)
	(anonymous function) (bundle.js:22:98714)
	(anonymous function) (bundle.js:31:3196)
	Ms (bundle.js:22:98671)
	Ts (bundle.js:22:98425)
	xs (bundle.js:22:97770)
	_s (bundle.js:22:96791)
	Za (bundle.js:22:95665)
	enqueueForceUpdate (bundle.js:22:45368)
	(anonymous function) (bundle.js:14:2010)
	value (bundle.js:92:182525)
	value
	value (dist.min.js:6:180021)
	value (dist.min.js:6:185547)
	value
	value (dist.min.js:6:158653)
	value (dist.min.js:6:155842)
	t (dist.min.js:6:157835)
```

**Comment by tsherif** [comment]
- [ ] This is the line that's tripping up Edge: https://github.com/uber/deck.gl/blob/master/modules/core/bundle/deckgl.js#L61

@Pessimistress any reason that wouldn't be transpiled anymore?

**Comment by tsherif** [comment]
- [ ] async/await stuff that's breaking IE is from this dependency in the json module: https://github.com/uber/deck.gl/blob/master/modules/json/package.json#L34
@Pessimistress @ajduberstein

**Comment by Pessimistress** [comment]
[Gallery](http://pessimistress.github.io/deck.gl/gallery/) issues:

- [ ] IconLayer example: not rendering
- [ ] PointCloudLayer example: not rendering
- [ ] Viewport transition example: no transition

**Comment by 1chandu** [comment]
AggregationLayer issues:
- [ ] Heatmap/Screengrid Examples don't render on data load (need to trigger another update to see data)
- [ ] GPUGridLayer cell positioning is wrong on when cellSize is changed (layer-browser)
- [ ] Heatmap layer doesn't render when zoom is 12 or more.
