### ISSUE TITLE
8.1 Release Tracker

### ISSUE THREAD

**Issue by 1chandu** [uber/deck.gl#4317]
- [x] Bump all dependencies (math.gl, probe.gl and loaders.gl) to latest release (@Pessimistress)
- [x] Publish alpha/beta  (@Pessimistress)
- [x] Bump all examples to latest alpha/beta (@Pessimistress)
- [x] Stage the website (@Pessimistress)
- [x] Verify whats-new (@Pessimistress)
- [x] Verify upgrade-guide (@Pessimistress)
- [x] Verify all issues in milestone are closed or move out (@tgorkin)
- [x] Verify all API changes are documented (@Pessimistress)
- [x] Website (docs and example) testing: [staging](http://pessimistress.github.io/deck.gl/#/)
    - [x] Testing on Chrome (@1chandu)
    - [x] Testing on Safari (@ 1chandu)
    - [x] Testing on Firefox (@1chandu)
    - [ ] Testing on Edge + IE11 (@tsherif)
    - [x] Testing on iOS (@Pessimistress)
    - [ ] Testing on Android (@Pessimistress)
- [x] Cut 8.1-release branch after all fixes (@Pessimistress)
- [x] Update website doc urls to point to `8.1-release` branch (@Pessimistress)
- [x] Publish 8.1 prod version.

Testing procedure
- access [staged doc website](http://pessimistress.github.io/deck.gl/)
- go through all examples and verify functionality in control panels
- go through all layers in [JSON playground](http://pessimistress.github.io/deck.gl/playground/)
- check visible results for regressions and console for errors/warnings
- add results of testing as comments on this issue

**Comment by 1chandu** [comment]
Chrome and Safari :

- [ ] `IconLayer`, `TextLayer` and `3DSurface Explorer` examples crash
```
bundle.js:27 TypeError: Class constructor CompositeLayer cannot be invoked without 'new'
    at new t (bundle.js:85)
```

**Comment by 1chandu** [comment]
Docs:
- [ ] 8.1 section in whats new.
- [ ] (Nit) Update mesh-layer/terrain-layers docs calrify picking/highlighting don't work as it is rendered as single instance.

Chrome:
- [ ] TextLayer example doesn't show all texts

<img width="1754" alt="Screen Shot 2020-03-14 at 11 58 33 AM" src="https://user-images.githubusercontent.com/9502731/76688944-e06bbb80-65ee-11ea-808c-10dbdc4875ce.png">

- [ ] MVTLayer: go do doc page, auto-highlighting works only in few zoom levels

**Comment by 1chandu** [comment]
Tested on Safari and Firefox, all good.
