### ISSUE TITLE
Events refactor followups

### ISSUE THREAD

**Issue by ericsoco** [uber/deck.gl#656]
This issue tracks followups to the [event handling refactor](https://github.com/uber/deck.gl/pull/636):

- [x] Currently, only one handler for an aliased event (only an issue for `'click'` for the foreseeable future) can exist at a time. Local state should be expanded to support an array of handlers against each aliased event. (#693)
- [X] Allow overriding recognizers in constructor. (#696)
- [x] Unit tests. (#705)
- [x] Changelog / docs.
- [x] Produce consistent Event object fields with custom input (currently wheel and pointermove). (#703)

Once landed, the following events-related work remains:
- [x] Fix [picking-on-every-event bug](https://github.com/uber/deck.gl/issues/634).
- [x] Move event handling from `deckgl.js` React wrapper into `layer-manager` so that non-React deck.gl consumers get event handling out of the box. (#738)
- [ ] Move per-layer handler calls from `draw-and-pick.js` into `layer-manager.js` event handlers added in #738
- [x] This PR breaks drag event handling, as drag events are not supported by Hammer.js out-of-the-box. That's ok, because drag events are [currently implemented incorrectly anyway](https://github.com/uber/deck.gl/issues/648). So, drag event handling needs to be refactored. (#738, #741, #742)
- [ ] Avoid reflows on (pointermove) event (@Pessimistress).
- [ ] Silence `passive` event warnings in Chrome.

**Comment by Pessimistress** [comment]
Importing from `deck.gl` breaks isomorphic rendering because hammer.js accesses `document`. Should we do a sanity check in EventManager?

**Comment by ericsoco** [comment]
Probably, yes -- don't see any reason anything in EventManager needs to (or can be expected to) work on the server.

Also, for reference: https://github.com/hammerjs/hammer.js/issues/930

**Comment by ericsoco** [comment]
See also:
- [ ] unit tests

**Comment by Pessimistress** [comment]
There is a bug with `mousemove`:
- Both `pointermove` and `mousemove` events are fired
- When dragging, an additional move event is fired from hammer.js
This causes picking to be triggered 3 times each frame during drag.

**Comment by shaojingli** [comment]
@Pessimistress can you do a pass on the remaining items listed in this issue tracker?

**Comment by ibgreen** [comment]
event handling is moved to mjolnir.js, let's track it there if needed.
