### ISSUE TITLE
deck.gl v4.1 release tracker

### ISSUE THREAD

**Issue by shaojingli** [uber/deck.gl#758]
CHANGES
- [x] Remove deck.gl's versions of common shader modules (fp64, fp32) and use luma's instead. - 
- [x] Fallback where WebGL2 is not supported
- [x] Default shader module
Ravi
- [x] update wind demo to use luma v4, add wind demo example to gallery - Yang
- [x] finish blog post - Shaojing

FIXES/CLEANUP
- [x] Source maps in demos are broken, again...
- [x] Build issue with demos (start-local: new Layer superclass constructor)
- [x] Remove lib bundle build target (not used) - from both deck and luma
- [x] PlotLayer example is not rendering labels (#790)
- [x] `updateTrigger` behavior change: when trigger key is invalid, now throws an error (4.1) instead of warn (4.0). Document or revert to old behavior?
- [x] withoutMap example doesn't work on Safari ( this is a bug in Safari )

DONE
- [x] Align deck.gl with luma.gl shader module system.
- [x] remove the dependency on gl-matrix and use separate modules
- [x] picking issue when `devicePixelRatio` changes (#418)

**Comment by shaojingli** [comment]
Please add tasks you feel that should block the release of deck.gl v4.1
