### ISSUE TITLE
Deck.gl v3 checklist

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#84]
Tentative release checklist for deck.gl v3 (currently being assembled on dev branch and published as v3.0.0-beta*)

**deck.gl**
- [x] Finalize copy (text) on main page
- [x] Finalize layout of main page
- [x] Core API improvements
  - [x] Fix meters mode (Layer methods + new methods on DeckGL)
  - [x] Finalize picking (Layer methods + new methods on DeckGL)
  - [x] Make all layers consistently use RGBA colors (instead of mix of RGB / RGBA)
  - [x] Move layers to new GLSL project function names, including fp64. 
  - [x] Enable layers to customize picking through `pick` lifecycle method
  - [x] new `LayerManager` class to enable deck.gl to be used without React.
  - [x] basic GLSL module manager `assembleShaders`
  - [x] Support multiple primitives in a layer
  - [x] Support composite layers
  - [x] Layer lifecycle cleanup
- [x] New documentation to replace the current API docs in README.MD
  - [x] Create "Getting Started" page
  - [x] Documentation of core layer props - one markdown file per layer
  - [x] Articles on using layers
  - [x] Articles on subclassing layers
  - [x] Article on coordinate systems and viewports
  - [x] Article on attribute management
  - [x] Article on writing deck.gl shaders
  - [x] Articles on using with React; using with Mapbox-gl; using standalone
  - [x] Article on Tips and Tricks
  - [x] Article on Performance
- [x] High-precision (64-bit) versions of core layers
  - [x] High-precision (64-bit) versions of ScatterplotLayer
  - [x] High-precision (64-bit) versions of ArcLayer
  - [x] High-precision (64-bit) versions of ChoroplethLayer
  - [x] High-precision (64-bit) versions of LineLayer
  - [x] High-precision (64-bit) versions of Extruded Choropleth Layer (building layer)
- [x] Fix broken layers
  - [x] Fix ArcLayer last segment flicker (32 bit)
  - [x] Fix ArcLayer last segment flicker (64 bit)
  - [x] Fix ScreenGridLayer
  - [x] Remove need to add 1 to z coordinate to render - Proj matrix far plane update
  - [x] Remove broken HexagonLayer
  - [x] Remove broken PointCloudLayer 
- [x] Examples
  - [x] TripsLayer example
  - [x] Add performance test layers to layer selector in example
- [x] shaderlib: 
  - [x] `fp64`: high-precision (64-bit) floating point calculation support
  - [x] `fp64`: intel, amd, nvidia testing and fixes

**viewport-mercator-project
  - [x] Fix METERS mode bug
  - [x] METERS coordinate system support
  - [x] Viewport class exported to `viewport-mercator-project` ([open PR](https://github.com/uber-common/viewport-mercator-project/pull/11))
  - [x] viewport as deck.gl context - avoids each layer recalculating viewport

**luma.gl**
- [x] Fix framebuffers

**react-map-gl**
- [x] Support non-cmd modifiers for perspective mode in react-map-gl.

**postponed**
- Fix framebuffer related examples
- Fix `project`/`unproject` error
- Meters proj mode examples - the current 32 bit examples are quite "wobbly"
- UNPROJECTED coordinate system support
- GeoJson layer improvement
- `fitBounds` replacement (that supports perspective)
- All dependencies on mapbox's internal transform class removed
- map-interactions independent of react-map-gl, used to control deck.gl visualizations without maps?

**Comment by contra** [comment]
Is the dev branch supposed to be runnable?

```
ERROR in ./~/deck.gl/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/index in /Users/contra/Projects/test/node_modules/deck.gl
 @ ./~/deck.gl/index.js 1:17-40
```

**Comment by ibgreen** [comment]
@contra `git checkout dev && git pull && npm install && npm start` works for me.
 
In some cases, you may need to do an `npm run build` to get the dist folder built, maybe it is that?

**Comment by contra** [comment]
@ibgreen Ah yeah, looks like the code on npm for `3.0.0-beta16` didn't have `npm run build` executed so there is no `dist` folder

**Comment by ibgreen** [comment]
3.0.0-rc5 looks like a good candidate.
